kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql  
 
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 20; done"]      

      containers:
      - name: backend
        image: joindevops/backend:v1.0
        resources: 
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"   
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   failureThreshold: 2
        #   periodSeconds: 5
        #   initialDelaySeconds: 60
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   failureThreshold: 2
        #   periodSeconds: 5
        #   initialDelaySeconds: 60
                             
        envFrom:
        - configMapRef:
            name: backend      

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port